spring.mongodb.uri=mongodb://catalogo-db:27017/catalogo_db
usuarios.ms.url=http://ms-usuarios:8080
pedido.ms.url=http://ms-pedido:8082
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/