spring.application.name=ms-catalogo
server.port=8081
server.servlet.context-path=/catalogoMs

# CONFIGURACIÓN DE LA BASE DE DATOS 
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/catalogo_db}
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# CONFIGURACIÓN SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.packages-to-scan=com.seminario.ms_catalogo.controller
springdoc.show-actuator=true

# CONFIGURACIÓN EUREKA
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}


# CONFIGURACIÓN DE MICROSERVICIOS EXTERNOS
usuarios.ms.url=${USUARIOS_MS_URL:http://localhost:8080}
pedido.ms.url=${PEDIDO_MS_URL:http://localhost:8082}

# CONFIGURACIÓN JWT
jwt.secret=${JWT_SECRET_KEY:c2VjcmV0b19zdXBlcl9segdyb19wYXJhX2Rlc2YXJyb2xsb19lbiVsYWN1bA==}
logging.level.org.springframework.security=DEBUG

management.endpoints.web.exposure.include=health,info,prometheus
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=Microservicio de Catálogo - Proyecto Analistas
info.app.version=0.0.1-SNAPSHOT

#CONFIGURACIÓN PROMETHEUS
management.metrics.tags.application=${spring.application.name}
