spring.application.name=ms-ia
server.port=8085
server.servlet.context-path=/iaMs

# CONFIGURACIÓN EUREKA
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

# CONFIGURACIÓN GROQ
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=openai/gpt-oss-20b

# CONFIGURACIÓN SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.packages-to-scan=com.seminario.ms_ia.controller
springdoc.show-actuator=true

# CONFIGURACIÓN JWT
jwt.secret=${JWT_SECRET_KEY}
logging.level.org.springframework.security=DEBUG

# CONFIGURACIÓN DE MICROSERVICIOS EXTERNOS
catalogo.ms.url=${CATALOGO_MS_URL:http://localhost:8081}

# CONFIGURACION DE CIRCUIT BREAKER (Resilience4j)
resilience4j.circuitbreaker.instances.catalogoClient.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.catalogoClient.slidingWindowSize=10
resilience4j.circuitbreaker.instances.catalogoClient.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.catalogoClient.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.catalogoClient.failureRateThreshold=50
resilience4j.circuitbreaker.instances.catalogoClient.slowCallRateThreshold=50
resilience4j.circuitbreaker.instances.catalogoClient.slowCallDurationThreshold=3s
resilience4j.circuitbreaker.instances.catalogoClient.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.catalogoClient.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.catalogoClient.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.catalogoClient.recordExceptions=org.springframework.web.client.HttpServerErrorException,org.springframework.web.client.ResourceAccessException,java.net.ConnectException,java.net.SocketTimeoutException,java.util.concurrent.TimeoutException
resilience4j.circuitbreaker.instances.catalogoClient.ignoreExceptions=org.springframework.web.client.HttpClientErrorException.BadRequest,org.springframework.web.client.HttpClientErrorException.Unauthorized,org.springframework.web.client.HttpClientErrorException.Forbidden,org.springframework.web.client.HttpClientErrorException.NotFound
resilience4j.retry.instances.catalogoClient.maxAttempts=4
resilience4j.retry.instances.catalogoClient.waitDuration=1s
resilience4j.retry.instances.catalogoClient.enableExponentialBackoff=true
resilience4j.retry.instances.catalogoClient.exponentialBackoffMultiplier=2
resilience4j.retry.instances.catalogoClient.retryExceptions=org.springframework.web.client.HttpServerErrorException,org.springframework.web.client.ResourceAccessException,java.net.ConnectException,java.net.SocketTimeoutException,java.util.concurrent.TimeoutException

logging.level.io.github.resilience4j=DEBUG

#CONFIGURACIÓN PROMETHEUS
management.endpoints.web.exposure.include=health,info,prometheus,circuitbreakers,circuitbreakerevents
management.metrics.tags.application=${spring.application.name}
