spring.application.name=ms-ia
server.port=8085
server.servlet.context-path=/iaMs

# CONFIGURACIÓN EUREKA
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

# CONFIGURACIÓN GROQ
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=openai/gpt-oss-20b

# CONFIGURACIÓN SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.packages-to-scan=com.seminario.ms_ia.controller
springdoc.show-actuator=true

# CONFIGURACIÓN JWT
jwt.secret=${JWT_SECRET_KEY:c2VjcmV0b19zdXBlcl9segdyb19wYXJhX2Rlc2YXJyb2xsb19lbiVsYWN1bA==}
logging.level.org.springframework.security=DEBUG

# CONFIGURACIÓN DE MICROSERVICIOS EXTERNOS
catalogo.ms.url=${CATALOGO_MS_URL:http://localhost:8081}

#CONFIGURACIÓN PROMETHEUS
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=${spring.application.name}
