services:
  # --- EUREKA (debe levantar primero) ---
  eureka-server:
    build: ../backend/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOST=eureka-server
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8761/ >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --- API GATEWAY ---
  api-gateway:
    build: ../backend/api-gateway
    container_name: api-gateway
    ports:
      - "8090:8090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - app-network
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "ps | grep 'java -jar app.jar' | grep -v grep"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --- MS USUARIOS ---
  ms-usuarios:
    build: ../backend/ms-usuarios
    container_name: ms-usuarios
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://usuario-db:5432/usuarios_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - CATALOGO_MS_URL=http://ms-catalogo:8081
      - PEDIDO_MS_URL=http://ms-pedido:8082
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker-1:9092
    depends_on:
      eureka-server:
        condition: service_healthy
      usuario-db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/usuariosMs/swagger-ui.html >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --- MS CATALOGO ---
  ms-catalogo:
    build: ../backend/ms-catalogo
    container_name: ms-catalogo
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATA_MONGODB_URI=mongodb://catalogo-db:27017/catalogo_db
      - USUARIOS_MS_URL=http://ms-usuarios:8080
      - PEDIDO_MS_URL=http://ms-pedido:8082
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker-1:9092
    depends_on:
      eureka-server:
        condition: service_healthy
      catalogo-db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8081/catalogoMs/swagger-ui.html >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --- MS PEDIDO (usa postgres + mongo) ---
  ms-pedido:
    build: ../backend/ms-pedido
    container_name: ms-pedido
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pedido-db:5432/pedidos_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATA_MONGODB_URI=mongodb://pedido-mongo-db:27017/pedido_db
      - USUARIOS_MS_URL=http://ms-usuarios:8080
      - CATALOGO_MS_URL=http://ms-catalogo:8081
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker-1:9092
    depends_on:
      eureka-server:
        condition: service_healthy
      pedido-db:
        condition: service_healthy
      pedido-mongo-db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8082/pedidoMs/swagger-ui.html >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --- MS PAGO ---
  ms-pago:
    build: ../backend/ms-pago
    container_name: ms-pago
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pago-db:5432/pago_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - USUARIOS_MS_URL=http://ms-usuarios:8080
      - CATALOGO_MS_URL=http://ms-catalogo:8081
      - PEDIDO_MS_URL=http://ms-pedido:8082
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker-1:9092
    depends_on:
      eureka-server:
        condition: service_healthy
      pago-db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8083/pagoMs/swagger-ui.html >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --- MS IA ---
  ms-ia:
    build: ../backend/ms-ia
    container_name: ms-ia
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pago-db:5432/pago_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - USUARIOS_MS_URL=http://ms-usuarios:8080
      - CATALOGO_MS_URL=http://ms-catalogo:8081
      - PEDIDO_MS_URL=http://ms-pedido:8082
    depends_on:
      eureka-server:
        condition: service_healthy
      ms-catalogo:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8085/iaMs/swagger-ui.html >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --- BASE DE DATOS USUARIOS (SQL) ---
  usuario-db:
    image: postgres:15-alpine
    container_name: usuario-db
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=usuarios_db # La BD se crea sola con este nombre
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./docker/data/usuarios:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d usuarios_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- BASE DE DATOS CATÁLOGO (NoSQL) ---
  catalogo-db:
    image: mongo:latest
    container_name: catalogo-db
    ports:
      - "27017:27017"
    volumes:
      - ./docker/data/catalogo:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping')\" localhost:27017/catalogo_db >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  # --- BASE DE DATOS PEDIDOS (SQL) ---
  pedido-db:
    image: postgres:15-alpine
    container_name: pedido-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=pedidos_db # La BD se crea sola con este nombre
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./docker/data/pedidos:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pedidos_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- BASE DE DATOS MS-PEDIDO (NoSQL) ---
  pedido-mongo-db:
    image: mongo:latest
    container_name: pedido-mongo-db
    ports:
      - "27018:27017"
    volumes:
      - ./docker/data/ms-pedido:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping')\" localhost:27017/pedido_db >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  # --- BASE DE DATOS PAGO (SQL) ---
  pago-db:
    image: postgres:15-alpine
    container_name: pago-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=pago_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./docker/data/pago:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pago_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- PROMETHEUS ---
  prometheus-server:
    build: ../backend/prometheus-server
    container_name: prometheus-server
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server
    networks:
      - app-network

  # --- GRAFANA ---
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - ../backend/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus-server
    networks:
      - app-network
  # --- LOKI ---
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ../backend/loki/loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network

  # --- PROMTAIL ---
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ../backend/promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - app-network


  # ==================== ZOOKEEPER ====================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==================== KAFKA BROKERS ====================
  kafka-broker-1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-broker-1
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # EN DEV. En PROD: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1      # EN DEV. En PROD: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1  # EN DEV. En PROD: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"    # fuerza creación manual
      KAFKA_LOG_RETENTION_HOURS: 168               # 7 días
      KAFKA_LOG_SEGMENT_BYTES: 1073741824          # 1GB
    ports:
      - "19092:9092"
      - "9092:9092"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "kafka-broker-version.sh", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092", "localhost:19092"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NOTA: En PROD añadir kafka-broker-2 y kafka-broker-3 con BROKER_ID: 2,3

  # ==================== KAFKA UI (OPCIONAL, RECOMENDADO) ====================
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka-broker-1
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-1:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    ports:
      - "8087:8080"
    networks:
      - app-network

  # ==================== TOPIC INIT ====================
  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-init
    depends_on:
      kafka-broker-1:
        condition: service_healthy
    volumes:
      - ./kafka/scripts/init-topics.sh:/scripts/init-topics.sh
    entrypoint: ["/bin/bash"]
    command: ["/scripts/init-topics.sh"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
volumes:
  kafka-data:
  zookeeper-data:
  kafka-broker-1-data: