server:
  port: 8090
  address: 0.0.0.0
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:3000"
                  - "http://192.168.0.198:3000"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true
          routes:
            - id: ms-pedido-ws
              uri: lb:ws://ms-pedido
              predicates:
                - Path=/pedidoMs/ws-notifications/**
                - Header=Upgrade, websocket
            - id: ms-usuarios
              uri: lb://ms-usuarios
              predicates:
                - Path=/usuariosMs/**
            - id: ms-catalogo
              uri: lb://ms-catalogo
              predicates:
                - Path=/catalogoMs/**
            - id: ms-pedido
              uri: lb://ms-pedido
              predicates:
                - Path=/pedidoMs/**
            - id: ms-pago
              uri: lb://ms-pago
              predicates:
                - Path=/pagoMs/**

# Configuración para que el Gateway se conecte a Eureka
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: API Gateway - Proyecto Analistas
    version: 0.0.1-SNAPSHOT